title: JL Christian
logo: /assets/img/jlc-avatar.png
email: person@address.com
description: Fine Artist | Art Curator
favicon: true
color-scheme: light

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: Introduction
    link: ./index.html#introduction
  - name: Artworks Codex | Feb 2019 - Mythos
    link: ./index.html##artworks-codex-|-feb-2019---mythos
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
