title: JL Christian
logo: /assets/img/jlc-avatar.png
email: <a class="mr.jonathanchristian@gmail.com></a>
description: Fine Artist | Art Curator
favicon: fulse
color-scheme: light

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/seiminomore
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/jonathanlejon/

navigation:
  - name: Portfolio Introduction
    link: ./portfolio-introduction.html
  - name: Index
    link: ./index.html
  - name: Artworks Codex
    link: ./artworks-codex.html
  - name: Art Direction
    link: ./art-direction.html
    sublist:
      - name: Case Study - Anime4Breakfast
        link: ./art-direction.html#case-study---anime4breakfast
      - name: Case Study - KC.93 RR
        link: ./art-direction.html#case-study---kc93-rr
      - name: Case Study - MDNKA Midnight Kids Academy
        link: ./art-direction.html#case-study---mdnka-midnight-kids-academy                                                        
  - name: Character Design & Storytelling
    link: ./character-design-&-storytelling.html
    sublist:
      - name: Case Study - BPH Battle Park High
        link: ./character-design-&-storytelling.html#case-study---bph-battle-park-high
